### ISSUE TITLE
Binding to an array of dates

### ISSUE THREAD

**Issue by ccrowhurstram** [bradberger/angular-material-calendar#11]
Any plans on adding support to `ng-model` bind to an array of dates?

Thanks
Christian

**Comment by bradberger** [comment]
Hmm... hadn't thought of that. Is it for selecting multiple dates? Could you provide an example of how you imagine it would work?

**Comment by bradberger** [comment]
Would be happy to add it, I guess I just don't quite understand how exactly it would be used, so any examples/comments would be helpful.

**Comment by ccrowhurstram** [comment]
Hi Brad,

I'm sure there's lots of use cases.

Specifically what I have in mind is for the calendar to present each date from the array highlighted on the calendar. Where the calendar is configured to allow the user to select their own dates, to update the bound array accordingly.

I think support for date *ranges* is another use case.

Christian

**Comment by bradberger** [comment]
Got it, that makes sense. I think it's certainly something that would add a lot of value, so I'll try to add it when I get a chance. PR's are welcomed, though, if it's something you or someone else would want to take a shot at.

**Comment by ccrowhurstram** [comment]
OK cool.

We're evaluating some calendar widgets at the moment. If we end up selecting your one then we will have a certain amount of time to add extra features.

Trying to be realistic - it's somewhat a catch-22: we're going to select a widget that has the least work to do...

Thanks
Christian

**Comment by bradberger** [comment]
Makes sense, will definitely see what I can do in the meantime...

**Comment by bradberger** [comment]
@ccrowhurstram Just added this in 7a064b18cfdc57334b1c880faf1200f3511c1e71 and the docs are on the website. Basically, though, to select multiple dates just need to initialize the `ngModel` in the parent scope as an array. It also now watches the parent `ngModel` which makes selecting dates programatically possible.

**Comment by christianacca** [comment]
Hey thanks brad for that, looks good.

Do you have a road map of features you are thinking of adding?

**Comment by bradberger** [comment]
No, not at this point. A range of dates is definitely on the to-do list, though. It's a personal project so I'm basically adding as needed, but I'm definitely open to requests/collaboration.

**Comment by christianacca** [comment]
OK cool
