### ISSUE TITLE
Get $templateUrl from $http

### ISSUE THREAD

**Issue by johnb0** [bradberger/angular-material-calendar#12]
I think, that parameter in $http.get() function should be "$scope.templateUrl", as we have it in condition above. 

Line 257 at source code:
if ($scope.templateUrl) {
                    $http
                      .get($scope.template)
                      .success(deferred.resolve)
                      .error(deferred.reject);
                }

**Comment by bradberger** [comment]
Yeah, you're absolutely right. Just fixed it and pushed the changes to both bower and npm. There's now a unit test for it, too. Thanks!
