### ISSUE TITLE
Every time I click on the day every day for the month is updating

### ISSUE THREAD

**Issue by ManiAkasapu** [bradberger/angular-material-calendar#14]
If I click on the a day to load events on that day, it is updating html for all days. Need a option to restrict update every time I click on the cell. 

Let me know if I am unclear.

**Comment by bradberger** [comment]
Yeah, I'm a bit unclear on what you mean. Could you explain?

**Comment by bradberger** [comment]
Never mind the previous question, this is fixed in 7a064b18cfdc57334b1c880faf1200f3511c1e71
