### ISSUE TITLE
Unable to update displayed data without re-loading the directive

### ISSUE THREAD

**Issue by gavinbarron** [bradberger/angular-material-calendar#21]
At present the HTML shown can only be set once per date per load. This makes it necessary to re-load the view containing the control to change the data displayed.

Suggest that we implement a data service to hold the data object currently on the directive scope and expose get/set methods to allow another component to alter the data to be shown after loading has completed.

**Comment by bradberger** [comment]
That makes a lot of sense. I'm all for it. Are you available to implement it?

**Comment by bradberger** [comment]
I definitely like the idea of extracting the data, as it makes the code a lot cleaner, and testing easier, too. The whole idea of displaying data was kind of an afterthought so I'm sure that it can be implemented a lot better than it currently is.

I've got a couple other proprietary projects right now that will prevent me from getting to this in the near future, so help is definitely requested :smile:

**Comment by bradberger** [comment]
Changes should be published to both bower and npm, as well as website updated now, too.
