### ISSUE TITLE
Columns displays broken when reducing size or on small screens

### ISSUE THREAD

**Issue by peio72** [bradberger/angular-material-calendar#24]
The columns display becomes broken if contains event when reducing the windows size or on small screens.
You can view the issue on the demo page by reducing the window.

**Comment by bradberger** [comment]
@peio72 Sorry, I'm trying to catch up on these items. I'm not seeing it locally on my browser. Is this still a problem you're having? I'm not sure if we've updated any code since opening the issue... Thanks!

**Comment by peio72** [comment]
Works fine now. Thanx.
