### ISSUE TITLE
Fill $scope variable with events from json on calendar init display

### ISSUE THREAD

**Issue by peio72** [bradberger/angular-material-calendar#25]
I’m trying to get a $scope variable feeded at first because I need his content for displaying the calendar but also for clicks on day:

Here is my code:

angular.module(‘myApp')
    .controller('agendaController', function ($scope, $mdSidenav, $rootScope, $state, $filter, $http) {

        $scope.events = [];
        $scope.showevent = false;

        $scope.dayevents = [];

        $scope.daytitle = '';

        $scope.dayFormat = "d";
        $scope.selectedDate = null;
        $scope.firstDayOfWeek = 1; // First day of the week, 0 for Sunday, 1 for Monday, etc.

        $http.get('./data/agenda.json')

        .success(function (data) {

                $scope.events = data;

            })
            .error(function (data, status, headers, config) {
                //  Do some error handling here
            });

        $scope.dayClick = function (date) {

            var numFmt = function (num) {
                num = num.toString();
                if (num.length < 2) {
                    num = "0" + num;
                }
                return num;
            };

            var key = [date.getFullYear(), numFmt(date.getMonth() + 1), numFmt(date.getDate())].join("-");

            //get events for the clicked date

            $scope.dayevents = $scope.events[key];

            $scope.daytitle = $filter("date")(date, "fullDate");

            if ($scope.dayevents) $scope.showevent = true;
            else $scope.showevent = false;

        };

        $scope.prevMonth = function (data) {
            $scope.msg = "You clicked (prev) month " + data.month + ", " + data.year;
            $scope.showevent = false;
        };

        $scope.nextMonth = function (data) {
            $scope.msg = "You clicked (next) month " + data.month + ", " + data.year;
            $scope.showevent = false;
        };

        $scope.setDayContent = function (date) {

            var numFmt = function (num) {
                num = num.toString();
                if (num.length < 2) {
                    num = "0" + num;
                }
                return num;
            };

            var key = [date.getFullYear(), numFmt(date.getMonth() + 1), numFmt(date.getDate())].join("-");

            var result = '';
            var disp_result = '';

            if ($scope.events[key]) {

                if ($scope.events[key].length > 1) {

                    for (i = 0; i < $scope.events[key].length; i++) {
                        result += '<span class="icon-hexagon event_category_' + $scope.events[key][i].category + '"></span>';
                    }
                } else {
                    result = '<span class="icon-hexagon event_category_' + $scope.events[key][0].category + '"></span>';
                }

            }

            if (result != '') disp_result = '<div class="events_result">' + result + '</div>';

            return $scope.events[key] ? disp_result : "";

        };

    })

 and agenda.json example:

{
    "2015-09-07": [{
        "name": "Labor Day",
        "category": 1,
        "date": "2015-09-07",
        "start": "13h15"
    }],
    "2015-09-11": [{
        "name": "Patriot Day",
        "category": 1,
        "date": "2015-09-11",
        "start": "09h15"
    }],
    "2015-09-13": [{
        "name": "Grandparent's Day",
        "category": 1,
        "date": "2015-09-13",
        "start": "08h15"
    }],
    "2015-09-17": [{
        "name": "Constitution Day",
        "category": 1,
        "date": "2015-09-17",
        "start": "13h35"
    }],
    "2015-10-06": [{
        "name": "German-American Day",
        "category": 1,
        "date": "2015-10-06",
        "start": "15h45"
    }],
    "2015-10-09": [{
        "name": "Leif Erkson Day",
        "category": 1,
        "date": "2015-10-09",
        "start": "11h00"
    }]
}

For the moment it's working only by clicking next/previous month but but not on the initial displayed month.

Thanx to help.

**Comment by gavinbarron** [comment]
Could you please create a plunkr or codepen to reproduce your issue?

**Comment by peio72** [comment]
I just need a working example using the var holidays filled by an external json file.
I can't find how to make this work with actual documentation.
Thanx for help.

**Comment by gavinbarron** [comment]
I'd start with having your holidays var set inline. That way you're eliminating the step of loading the .json file. Once that's working then add the loading from an external file.

**Comment by peio72** [comment]
Yes that's what i did; Adding loading the json makes default month empty. Works only after by clicking next month. If you have an idea how to make it works with json loading, examples and documentation are not quite clear on those points. Thanx.

**Comment by peio72** [comment]
Any chance I get the var holidays filled with http json before setDayContant run ? I don't see how to make this work. Documentation not clear. Please help.

**Comment by luchopintado** [comment]
Try this:
&lt;calendar-md flex layout layout-fill
  ng-if="showCalendar"
 ....
&lt;/calendar-md&gt;

JS:
service.getList().then(function(result) {
    //Fill your array...
   $scope.showCalendar = true;
});

**Comment by peio72** [comment]
It's working !! Thanx a lot.
