### ISSUE TITLE
Rows in Calendar View when using IE/Edge are too tall

### ISSUE THREAD

**Issue by gavinbarron** [bradberger/angular-material-calendar#26]
As a result the container is overflowed and a scroll bar is introduced

**Comment by gavinbarron** [comment]
#27  addresses this

**Comment by bradberger** [comment]
@gavinbarron This was merged, so I think it can be closed, correct? If not, feel free to reopen.

**Comment by gavinbarron** [comment]
Yes, we are good to close that issue
