### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by amellini** [bradberger/angular-material-calendar#29]
Hi all,
I'm testing this component but I need a different localization,there's a way to do that?
I haven't find any way in the documentation, i've missed something?

**Comment by bradberger** [comment]
Actually the dates are passed through the [Angular date filter](https://docs.angularjs.org/api/ng/filter/date) for display, so [standard Angular i18n](https://docs.angularjs.org/guide/i18n) should apply. Hence, you should be able to use whatever localization you need by just including it as described in the Angular docs.
