### ISSUE TITLE
md-calendar collides with md-calendar in angular-material 0.11.0

### ISSUE THREAD

**Issue by gavinbarron** [bradberger/angular-material-calendar#3]
0.11.0 introduces an md-calendar directive, this collides with this directive.

Technically we (the wider community) should not be using the md- namespace in much the same way that we're not supposed to use the ng namespace, they're reserved (in theory) for those projects.

Anyway I really like your project and and like the ability to inject content into the calendar easily. So I propose a simple change from md-calendar to calendar-md as seen in my PR.

Cheers

**Comment by bradberger** [comment]
Good point, just merged the PR. As mentioned on the PR, didn't realize that anyone would actually end up using this, so naming was never a consideration. Thanks!

**Comment by bradberger** [comment]
@gavinbarron Would be happy to add you as a collaborator if you'd be interested, it would be great to have more hands on board if people are actually using this!

**Comment by gavinbarron** [comment]
Yeah, happy to contribute where I can. Am using this on a project at the moment so may have a few more contributions to make.

**Comment by bradberger** [comment]
Awesome, thanks. Glad to hear that. Have it at! Any improvements you have are most welcome!
