### ISSUE TITLE
Next Month Function

### ISSUE THREAD

**Issue by Dan-Hodges** [bradberger/angular-material-calendar#5]
The Next month function doesn't work. In the angular-material-calendar.js file, the month is increased by 2, which actually displays the current month.

**Comment by bradberger** [comment]
Just wanted to follow up on this, since the PR is closed, what's the status of the issue? Are you still finding that it doesn't work?

**Comment by bradberger** [comment]
Going to close this for now, every test I've run on it makes it seem like it's working, but if we can come across some scenarios where it's not correct, by all means let's reopen the issue.
