### ISSUE TITLE
First day of week parameter

### ISSUE THREAD

**Issue by brunoaduarte** [bradberger/angular-material-calendar#7]
Is there a way to set the first day of the week ? With the default layout it starts at Saturday

**Comment by bradberger** [comment]
Not yet, that's actually the largest item on the to-do list, feature wise. Will try to get to it in the near future, but PR's are welcomed, too :smile:

**Comment by bradberger** [comment]
Added this just now, feel free to try it out and let me know what you find. Haven't had to test it extensively, but so far so good.

**Comment by brunoaduarte** [comment]
Awesome, thanks Brad.
