### ISSUE TITLE
Calendar starts at wrong month

### ISSUE THREAD

**Issue by brunoaduarte** [bradberger/angular-material-calendar#8]
When i run the page with the calendar, it starts with the previous month.

**Comment by bradberger** [comment]
Would it be possible to post a code sample demonstrating the issue (using JSBin, jsfiddle, etc.)? Thanks!

**Comment by ManiAkasapu** [comment]
Removing these 2 will work.
`<  data-start-month="8"
     data-start-year="2014">`

**Comment by ManiAkasapu** [comment]
By the way @bradberger  thanks for awesome plugin. If you improve a bit would be best mobile calendar plugin.

**Comment by bradberger** [comment]
Should be fixed in 554431ef673cb26a20432f854a581d010ecbb30c. Did a major refactor on dates, and should be a lot more stable even across timezones now.
